---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://172.20.0.10:80"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
  
jobs:
  - type: import                     
    parameters:
      type: 'url'                    
      fileName: '/zap/wrk/url'
      
  - type: passiveScan-config           # Passive scan configuration
    parameters:
      maxAlertsPerRule: 10             # Int: Maximum number of alerts to raise per rule
      scanOnlyInScope: false            # Bool: Only scan URLs in scope (recommended)
      maxBodySizeInBytesToScan:        # Int: Maximum body size to scan, default: 0 - will scan all messages
    rules:                             # A list of one or more passi
    
  - type: passiveScan-wait             # Passive scan wait for the passive scanner to finish
    parameters:
      maxDuration: 5                   # Int: The max time to wait for 
      
  - type: outputSummary                # Print summary to stdout, primarily to mimic the behaviour of the packaged scans
    parameters:
      format: Long                    # String: The format of the output, one of None, Short, Long, default: None
      summaryFile: /zap/wrk/report.json                     # String: The full path of a file into which will be written a JSON summary of the scan, default empty
  
  - type: report                       # Report generation
    parameters:
      template: traditional-json    # String: The template id, default : traditional-html
      reportDir: /zap/wrk    # String: The directory into which the report will be written
      reportFile:                      # String: The report file name pattern, default: {yyyy-MM-dd}-ZAP-Report-[[site]]
      reportTitle:                     # String: The report title
      reportDescription:               # String: The report description
      displayReport:               # Boolean: Display the report when generated, default: false
    risks:                             # List: The risks to include in this report, default all
      - high
      - medium
      - low
      - info
    confidences:                       # List: The confidences to include in this report, default all
      - high
      - medium
      - low
      - falsepositive
    sections:
