---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "https://httpbin.org"
    - "https://google.com"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
  
jobs:
  - type: import                     
    parameters:
      type: 'url'                    
      fileName: '/zap/wrk/url'     
