---
version: "3"
services:
  juiceshop:
    image: bkimminich/juice-shop
    networks:
      test:
        ipv4_address: 172.20.0.12
    ports:
      3000:80
    
  nginx-1:
    image: nginx
    networks:
      test:
        ipv4_address: 172.20.0.11
    ports:
      - 8000:80
    volumes:
      - ./src:/usr/share/nginx/html
  nginx-2:
    image: nginx
    networks:
      test:
        ipv4_address: 172.20.0.10
        
        
    ports:
      - 8001:80
    volumes:
      - ./src:/usr/share/nginx/html
networks:
  test:
    name: test
    external: true
