name: owasp-zap

on:
  push:
    branches:
    - main
    
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions: 
      issues: write    
      
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Creating Docker Network
      run: docker network create --subnet=172.20.0.0/16 test

    - name: Build Docker Image
      run: docker-compose -f "docker-compose.yaml" up -d --build
      
    - name: Check the image are running
      run: docker ps

    - name: Fetch IP
      id: fetchip
      run: |
        for ip in 172.20.0.10 172.20.0.11; do
          echo "${ip}"
        done
    - name: url check
      run: curl http://$|{{ steps.fetchip.ip}}:80
    - name: OWASP ZAP Docker pull
      run: docker pull owasp/zap2docker-stable
      
    - name: Run Scan against URLs
      run: docker run --net test -t owasp/zap2docker-stable zap-baseline.py -I -d -t http://${{steps.file.outputs.ip}}:80
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
      
    
