name: owasp-zap

on:
  push:
    branches:
    - main
    
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Creating Docker Network
      run: docker network create test
      
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    
    - name: Build Docker Image
      run: docker-compose -f "docker-compose.yaml" up -d --build
      
    - name: Check the image are running
      run: docker ps
      
    - name: Health check nginx-1
      run: curl http://127.0.0.1:8000
    
    - name: Health check nginx-2
      run: curl http://127.0.0.1:8001
      
    - name: IP address
      id: fetchip
      run: |
        ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' owasp-sap_nginx-1_1) 
        echo ::set-output name=ip::$ip
    
    - name: OWASP ZAP Docker pull
      run: docker pull owasp/zap2docker-stable
      
    - name: Run Scan against URLs
      run: docker run --net test -v $(pwd):/zap/wrk/:rw \
          -t owasp/zap2docker-stable zap-full-scan.py -I -j -m 10 -T 60 \
          -t http://${{ steps.fetchip.outputs.ip }}:80 \
          -r 20210417-zap-full-scan-without-user.html
      
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
      
    
