name: owasp-zap

on:
  push:
    branches:
    - main
    
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions: 
      issues: write    
      
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Creating Docker Network
      run: docker network create --subnet=172.20.0.0/16 test

    - name: Build Docker Image
      run: docker-compose -f "docker-compose.yaml" up -d --build
      
    - name: Check the image are running
      run: docker ps

    - name: Create temp directory
      run: 
        sudo chown -R 1000:1000 zap-config
        
    - name: Validate access to vol
      run:
        docker run --net test --user zap -v ${{ github.workspace }}/zap-config:/zap/wrk/:rw -t owasp/zap2docker-stable sudo chmod 777 /zap/wrk/zap.yaml; cat /zap/wrk/zap.yaml
        
    - name: Run Scan against URLs
      run: |
        docker run --net test --user zap -v ${{ github.workspace }}/zap-config:/zap/wrk:rw -t owasp/zap2docker-stable  zap.sh -cmd -autorun /zap/wrk/zap.yaml
    
    - name: Archive DAST Scan results
      uses: actions/upload-artifact@v3
      with:
        name: DAST-scan-report
        path: /home/runner/work/owasp-sap/owasp-sap/zap/report-*.json
          
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
      
    
