name: owasp-zap

on:
  push:
    branches:
    - main
    
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Docker Image
      run: docker-compose -f "docker-compose.yaml" up -d --build
      
    - name: Check the image are running
      run: docker ps
      
    - name: Health check
      run: curl http://localhost:8000
    
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'http://localhost:8000'
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
      
    
