name: owasp-zap
env:
  VALUE_ARRAY_AS_STRING: 'http://127.0.0.1:8000,http://127.0.0.1:8001'

on:
  push:
    branches:
    - main
    
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Docker Image
      run: docker-compose -f "docker-compose.yaml" up -d --build
      
    - name: Check the image are running
      run: docker ps
      
    - name: Health check nginx-1
      run: curl http://127.0.0.1:8000
    
    - name: Health check nginx-2
      run: curl http://127.0.0.1:8001
    
    - name: OWASP ZAP Baseline Scan
      # You may pin to the exact commit or the version.
      # uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: IFS="," read -a myarray <<< ${{ env.VALUE_ARRAY_AS_STRING }}
        fail_action: false
        allow_issue_writing: false
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
      
    
