name: owasp-zap

on:
  push:
    branches:
    - main
    
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Creating Docker Network
      run: docker network create test
      
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    
    - name: Build Docker Image
      run: docker-compose -f "docker-compose.yaml" up -d --build
      
    - name: Check the image are running
      run: docker ps
            
    - name: IP address
      id: fetchip
      run: |
        ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' owasp-sap_nginx-1_1) 
        echo ::set-output name=ip::$ip
      
    - name: Health check nginx-1
      run: curl http://${{ steps.fetchip.outputs.ip }}:8000
    
    - name: Health check nginx-2
      run: curl http://${{ steps.fetchip.outputs.ip }}:8001
    
    - name: OWASP ZAP Docker pull
      run: docker pull owasp/zap2docker-stable
      
    - name: Run Scan against URLs
      run: docker run -d -t owasp/zap2docker-stable
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
      
    
