name: pr_checker

on:
  push:
  workflow_dispatch:
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: Check if PR exists
        id: pr_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
                --repo ${{ github.repository }} \
                --json baseRefName,headRefName \
                --jq '
                    map(select(.baseRefName == "main" and .headRefName == "${{ github.ref_name }}" ))
                    | length
                ')
            if [ ${prs} > 0 ]; then
                echo "skip=true" >> "$GITHUB_OUTPUT"
            fi
      - name: Create pull request
        if: '!steps.check.outputs.skip'
        run: echo "no pr open for this branch ok"
      - name: Dont create pull request
        if: 'steps.check.outputs.skip'
        run: echo "pr open for this branch ok"

